on: pull_request

jobs:
     
  pipeline-scan:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@master
      - name: Set up JDK 1.8 
        uses: actions/setup-java@v1       
        with:
          java-version: 1.8
      - name: Download the Pipeline Scanner
        uses: wei/curl@master
        with:
          args: -O https://downloads.veracode.com/securityscan/pipeline-scan-LATEST.zip
      - name: Unzip the Pipeline Scanner
        run: unzip pipeline-scan-LATEST.zip
      - name: show environment
        run: env
      - name: Run Pipeline Scanner
        run: java -jar pipeline-scan.jar -vid "${{ secrets.VERACODE_API_ID }}" -vkey "${{ secrets.VERACODE_API_KEY }}" --file "target/verademo.war" --fail_on_severity="Very High, High"
      - name: echo Var
        run: echo $PIPELINE_OUTPUT
