on: pull_request

jobs:
     
  pipeline-scan:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@master
      - name: Set up JDK 1.8 
        uses: actions/setup-java@v1       
        with:
          java-version: 1.8
      - name: Download the Pipeline Scanner
        uses: wei/curl@master
        with:
          args: -O https://downloads.veracode.com/securityscan/pipeline-scan-LATEST.zip
      - name: Unzip the Pipeline Scanner
        run: unzip pipeline-scan-LATEST.zip
      - name: Run Pipeline Scanner and reformat json
        run: | 
          chmod +x .github/files/json.sh .github/files/jq-linux64
          java -jar pipeline-scan.jar -vid "${{ secrets.VERACODE_API_ID }}" -vkey "${{ secrets.VERACODE_API_KEY }}" --file "target/verademo.war" --fail_on_severity="Very High, High" -jf .github/files/results.json 
          cd .github/files
          .github/files/json.sh
          ls -laR
      - uses: github/codeql-action/upload-sarif@v1
        if: ${{ always() }}
        with:
          sarif_file: .github/files/veracode-sarif.json
